name: z5-build-env
channels:
  - conda-forge
dependencies:
  - cmake
  - compilers
  - bzip2
  - lz4-c
  - xz
  - zlib
  - xtensor >=0.24,<0.25
  - xtensor-python >=0.26,<0.27
  - xsimd >=10,<11
  - blosc
  - imageio
  - nlohmann_json
  - zarr <3
  - h5py
